import "../globals.css";
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import AudioProvider from "../providers/AudioProvider";
import SearchProvider from "../providers/SearchProvider";
import RatingProvider from "../providers/RatingProvider";
import SessionProvider from "@/app/providers/SessionProvider";
import NextUIProviderWrapper from "../providers/NextUIProvider";
import UserDBInfoProvider from "../providers/UserDBInfoProvider";

const manrope = Manrope({ subsets: ["latin"], weight: ["200", "300", "400", "500", "600", "700", "800"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  // can probably morph all providers into one provider?
  return (
    <SessionProvider>
      <AudioProvider>
        <html lang="en" className="dark">
          <head>
            <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1"></meta>
          </head>
          <body className={manrope.className}>
            <NextUIProviderWrapper>
              <UserDBInfoProvider>
                <SearchProvider>
                  <RatingProvider>
                    {children}
                  </RatingProvider>
                </SearchProvider>
              </UserDBInfoProvider>
            </NextUIProviderWrapper>
          </body>
        </html>
      </AudioProvider>
    </SessionProvider>
  );
}
